# This script aims to add manual annotation to the csv file generated by 'rat_video_segmentation_rotation1.py'

import numpy as np
import csv
import pandas as pd



def add_manual_annoation(featureFileName,annoationFileName):
    features = pd.read_csv(featureFileName)
    frameNum = features.shape[0]
    manualAnnotation_file = open(annoationFileName,"r")
    lines = manualAnnotation_file.readlines()
    animals = ['NaN']*int(frameNum)
    for line in lines:
        print line
        startTimeStr, endTimeStr, stage = line.split(' ')
        stage = stage.rstrip()
        startTimeStrs = startTimeStr.split(':')
        endTimeStrs = endTimeStr.split(':')
        startTime = float(startTimeStrs[0])*3600+float(startTimeStrs[1])*60 + float(startTimeStrs[2])+float(startTimeStrs[3])*0.01
        endTime = float(endTimeStrs[0])*3600+float(endTimeStrs[1])*60 + float(endTimeStrs[2])+float(endTimeStrs[3])*0.01
        startFrame = int(startTime*15.0)
        endFrame = int(endTime*15.0) 
        animals[startFrame:endFrame] = [stage]*(endFrame-startFrame)
  
    features['animal'] = animals
    features.to_csv(featureFileName)
    

featureFileName = 'C:\\PostDoctorProjects\\VideoEEGData\\Shank2_20150609\\video_stitched\\Shan2_20150609_out_bottom.csv'
annoationFileName = 'C:\\PostDoctorProjects\\VideoEEGData\\Shank2_20150609\\video_stitched\\valid_time_period_Right.txt' 
add_manual_annoation(featureFileName,annoationFileName)